/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package plantapp;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;

/**
 *
 * @author WINDOWS
 */
public class ADMIN_dashboard extends javax.swing.JFrame {
    connection dbConn;

    /**
     * Creates new form USER_login
     */
    public ADMIN_dashboard() {
        initComponents();
        
        // Connects once again!
        dbConn = new connection();
        dbConn.ActivateConn();
        
        System.out.println("Session email: " + ALL_login.sessionEmail);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        email_lbl = new javax.swing.JLabel();
        loginbtn1 = new javax.swing.JButton();
        ctlgmngr = new javax.swing.JButton();
        email_lbl2 = new javax.swing.JLabel();
        email_lbl3 = new javax.swing.JLabel();
        accrec = new javax.swing.JButton();
        adacc = new javax.swing.JButton();
        ordmngr = new javax.swing.JButton();
        stockmngr = new javax.swing.JButton();
        email_lbl1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainpanel.setBackground(new java.awt.Color(238, 235, 235));
        mainpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/LOGO_main.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        mainpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 340, -1));

        email_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        email_lbl.setForeground(new java.awt.Color(72, 96, 51));
        email_lbl.setText("Employee Portal");
        mainpanel.add(email_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, 30));

        loginbtn1.setBackground(new java.awt.Color(72, 96, 51));
        loginbtn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginbtn1.setForeground(new java.awt.Color(255, 255, 255));
        loginbtn1.setText("Log Out");
        loginbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtn1ActionPerformed(evt);
            }
        });
        mainpanel.add(loginbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 300, -1));

        ctlgmngr.setBackground(new java.awt.Color(72, 96, 51));
        ctlgmngr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ctlgmngr.setForeground(new java.awt.Color(255, 255, 255));
        ctlgmngr.setText("Catalogue Manager");
        ctlgmngr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctlgmngrActionPerformed(evt);
            }
        });
        mainpanel.add(ctlgmngr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 300, -1));

        email_lbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email_lbl2.setForeground(new java.awt.Color(72, 96, 51));
        email_lbl2.setText("What do you want to manage?");
        mainpanel.add(email_lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        email_lbl3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email_lbl3.setForeground(new java.awt.Color(72, 96, 51));
        email_lbl3.setText("Done with work?");
        mainpanel.add(email_lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        accrec.setBackground(new java.awt.Color(72, 96, 51));
        accrec.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        accrec.setForeground(new java.awt.Color(255, 255, 255));
        accrec.setText("Account Records");
        accrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accrecActionPerformed(evt);
            }
        });
        mainpanel.add(accrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 300, -1));

        adacc.setBackground(new java.awt.Color(72, 96, 51));
        adacc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adacc.setForeground(new java.awt.Color(255, 255, 255));
        adacc.setText("Create an Admin Account");
        adacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaccActionPerformed(evt);
            }
        });
        mainpanel.add(adacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 300, -1));

        ordmngr.setBackground(new java.awt.Color(72, 96, 51));
        ordmngr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ordmngr.setForeground(new java.awt.Color(255, 255, 255));
        ordmngr.setText("Order Manager");
        ordmngr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordmngrActionPerformed(evt);
            }
        });
        mainpanel.add(ordmngr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 300, -1));

        stockmngr.setBackground(new java.awt.Color(72, 96, 51));
        stockmngr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        stockmngr.setForeground(new java.awt.Color(255, 255, 255));
        stockmngr.setText("Stock Manager");
        stockmngr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockmngrActionPerformed(evt);
            }
        });
        mainpanel.add(stockmngr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 300, -1));

        email_lbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        email_lbl1.setForeground(new java.awt.Color(72, 96, 51));
        email_lbl1.setText("Portal Dashboard");
        mainpanel.add(email_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        getContentPane().add(mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 760));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/BG_user.png"))); // NOI18N
        jLabel3.setText("jLabel2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -130, -1, -1));

        setSize(new java.awt.Dimension(1063, 765));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtn1ActionPerformed
        // TODO add your handling code here:
        ALL_login login = new ALL_login();
        this.dispose();
        login.setVisible(true);
        try {
            dbConn.conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(ADMIN_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginbtn1ActionPerformed

    private void ordmngrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordmngrActionPerformed
        // TODO add your handling code here:
        ADMIN_ordermanager ordman = new ADMIN_ordermanager();
        this.dispose();
        ordman.setVisible(true);
        try {
            dbConn.conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(ADMIN_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ordmngrActionPerformed

    private void stockmngrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockmngrActionPerformed
        // TODO add your handling code here:
        ADMIN_stockmanager stockman = new ADMIN_stockmanager();
        this.dispose();
        stockman.setVisible(true);
        try {
            dbConn.conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(ADMIN_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_stockmngrActionPerformed

    private void ctlgmngrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctlgmngrActionPerformed
        // TODO add your handling code here:
        ADMIN_cataloguemanager catman = new ADMIN_cataloguemanager();
        this.dispose();
        catman.setVisible(true);
        try {
            dbConn.conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(ADMIN_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ctlgmngrActionPerformed

    private void accrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accrecActionPerformed
        // TODO add your handling code here:
        try {
            String stmt = "SELECT ACC_TYPE FROM ACCOUNTS WHERE EMAIL = ?";
            PreparedStatement pstmt = dbConn.conn.prepareStatement(stmt);
            pstmt.setString(1, ALL_login.sessionEmail);
            
            ResultSet rs = pstmt.executeQuery();
            String sessionAccType = rs.getString("ACC_TYPE");
            
            if (sessionAccType.equals("MANAGER")) {
                System.out.println("Welcome Manager!");
                ADMIN_accountrecords accrecs = new ADMIN_accountrecords();
                this.dispose();
                accrecs.setVisible(true);
                dbConn.conn.close();
            } else {
                JOptionPane.showMessageDialog(null, "Unable to access. You don't have permission.");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ADMIN_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_accrecActionPerformed

    private void adaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaccActionPerformed
        // TODO add your handling code here:
        try {
            String stmt = "SELECT ACC_TYPE FROM ACCOUNTS WHERE EMAIL = ?";
            PreparedStatement pstmt = dbConn.conn.prepareStatement(stmt);
            pstmt.setString(1, ALL_login.sessionEmail);
            
            ResultSet rs = pstmt.executeQuery();
            String sessionAccType = rs.getString("ACC_TYPE");
            
            if (sessionAccType.equals("MANAGER")) {
                System.out.println("Welcome Manager!");
                ADMIN_accountsetup acset = new ADMIN_accountsetup();
                this.dispose();
                acset.setVisible(true);
                dbConn.conn.close();
            } else {
                JOptionPane.showMessageDialog(null, "Unable to access. You don't have permission.");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ADMIN_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_adaccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(ADMIN_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(ADMIN_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(ADMIN_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(ADMIN_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
            
            
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new ADMIN_dashboard().setVisible(true);
                }
            });
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ADMIN_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ADMIN_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ADMIN_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ADMIN_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accrec;
    private javax.swing.JButton adacc;
    private javax.swing.JButton ctlgmngr;
    private javax.swing.JLabel email_lbl;
    private javax.swing.JLabel email_lbl1;
    private javax.swing.JLabel email_lbl2;
    private javax.swing.JLabel email_lbl3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginbtn1;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JButton ordmngr;
    private javax.swing.JButton stockmngr;
    // End of variables declaration//GEN-END:variables
}
