/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package plantapp;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author WINDOWS
 */
public class ADMIN_accountsetup extends javax.swing.JFrame {
    
    
    /**
     * Creates new form USER_login
     */
    public ADMIN_accountsetup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainpanel = new javax.swing.JPanel();
        confirmlbl = new javax.swing.JLabel();
        confirmpass = new javax.swing.JTextField();
        email_lbl = new javax.swing.JLabel();
        regfinish = new javax.swing.JButton();
        lnamelbl = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        emaillbl = new javax.swing.JLabel();
        invald_names = new javax.swing.JLabel();
        bday = new com.toedter.calendar.JDateChooser();
        fnamelbl = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        pass_lbl = new javax.swing.JLabel();
        bdaylbl1 = new javax.swing.JLabel();
        invalid_email = new javax.swing.JLabel();
        invalid_bday = new javax.swing.JLabel();
        invalid_pass = new javax.swing.JLabel();
        invalid_confirm = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainpanel.setBackground(new java.awt.Color(238, 235, 235));
        mainpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirmlbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmlbl.setForeground(new java.awt.Color(72, 96, 51));
        confirmlbl.setText("Confirm Password");
        mainpanel.add(confirmlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        confirmpass.setBackground(new java.awt.Color(255, 255, 255));
        confirmpass.setForeground(new java.awt.Color(72, 96, 51));
        confirmpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpassActionPerformed(evt);
            }
        });
        mainpanel.add(confirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 280, 20));

        email_lbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        email_lbl.setForeground(new java.awt.Color(72, 96, 51));
        email_lbl.setText("Admin Account Setup");
        mainpanel.add(email_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        regfinish.setBackground(new java.awt.Color(72, 96, 51));
        regfinish.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        regfinish.setForeground(new java.awt.Color(255, 255, 255));
        regfinish.setText("Finish");
        mainpanel.add(regfinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, -1, -1));

        lnamelbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lnamelbl.setForeground(new java.awt.Color(72, 96, 51));
        lnamelbl.setText("Last Name");
        mainpanel.add(lnamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        lname.setBackground(new java.awt.Color(255, 255, 255));
        lname.setForeground(new java.awt.Color(72, 96, 51));
        mainpanel.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 130, 20));

        email1.setBackground(new java.awt.Color(255, 255, 255));
        email1.setForeground(new java.awt.Color(72, 96, 51));
        mainpanel.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 280, 20));

        fname.setBackground(new java.awt.Color(255, 255, 255));
        fname.setForeground(new java.awt.Color(72, 96, 51));
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        mainpanel.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 130, 20));

        emaillbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emaillbl.setForeground(new java.awt.Color(72, 96, 51));
        emaillbl.setText("Email");
        mainpanel.add(emaillbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        invald_names.setForeground(new java.awt.Color(158, 31, 31));
        invald_names.setText("Either fields cannot be empty.");
        mainpanel.add(invald_names, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        bday.setBackground(new java.awt.Color(255, 255, 255));
        bday.setForeground(new java.awt.Color(72, 96, 51));
        mainpanel.add(bday, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 280, 20));

        fnamelbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fnamelbl.setForeground(new java.awt.Color(72, 96, 51));
        fnamelbl.setText("First Name");
        mainpanel.add(fnamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        pass.setBackground(new java.awt.Color(255, 255, 255));
        pass.setForeground(new java.awt.Color(72, 96, 51));
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        mainpanel.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 280, 20));

        pass_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pass_lbl.setForeground(new java.awt.Color(72, 96, 51));
        pass_lbl.setText("Password");
        mainpanel.add(pass_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        bdaylbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bdaylbl1.setForeground(new java.awt.Color(72, 96, 51));
        bdaylbl1.setText("Birthday");
        mainpanel.add(bdaylbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        invalid_email.setForeground(new java.awt.Color(158, 31, 31));
        invalid_email.setText("Must be a valid email.");
        mainpanel.add(invalid_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        invalid_bday.setForeground(new java.awt.Color(158, 31, 31));
        invalid_bday.setText("Must be 16 or older.");
        mainpanel.add(invalid_bday, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        invalid_pass.setForeground(new java.awt.Color(158, 31, 31));
        invalid_pass.setText("Must be 8 to 12 characters.");
        mainpanel.add(invalid_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, -1, -1));

        invalid_confirm.setForeground(new java.awt.Color(158, 31, 31));
        invalid_confirm.setText("Must match password.");
        mainpanel.add(invalid_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, -1, -1));

        getContentPane().add(mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 760));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/BG_user.png"))); // NOI18N
        jLabel3.setText("jLabel2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -130, -1, -1));

        setSize(new java.awt.Dimension(1063, 765));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmpassActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(ADMIN_accountsetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(ADMIN_accountsetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(ADMIN_accountsetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(ADMIN_accountsetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            
            
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new ADMIN_accountsetup().setVisible(true);
                }
            });
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ADMIN_accountsetup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ADMIN_accountsetup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ADMIN_accountsetup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ADMIN_accountsetup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser bday;
    private javax.swing.JLabel bdaylbl1;
    private javax.swing.JLabel confirmlbl;
    private javax.swing.JTextField confirmpass;
    private javax.swing.JTextField email1;
    private javax.swing.JLabel email_lbl;
    private javax.swing.JLabel emaillbl;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel fnamelbl;
    private javax.swing.JLabel invald_names;
    private javax.swing.JLabel invalid_bday;
    private javax.swing.JLabel invalid_confirm;
    private javax.swing.JLabel invalid_email;
    private javax.swing.JLabel invalid_pass;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lname;
    private javax.swing.JLabel lnamelbl;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JTextField pass;
    private javax.swing.JLabel pass_lbl;
    private javax.swing.JButton regfinish;
    // End of variables declaration//GEN-END:variables
}
