/*
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package plantapp;

/**
 *
 * @author WINDOWS
 */
public class USER_aboutus extends javax.swing.JFrame {

    /**
     * Creates new form USER_login
     */
    public USER_aboutus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        email_lbl = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        confirmlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainpanel.setBackground(new java.awt.Color(238, 235, 235));
        mainpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        email_lbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        email_lbl.setForeground(new java.awt.Color(72, 96, 51));
        email_lbl.setText("About Us");
        mainpanel.add(email_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        loginbtn.setBackground(new java.awt.Color(72, 96, 51));
        loginbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        loginbtn.setText("Return");
        mainpanel.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/LOGO_login.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        mainpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 280, 261));

        confirmlbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmlbl.setForeground(new java.awt.Color(72, 96, 51));
        confirmlbl.setText("<html>The Garden Haus is a cozy flower and plant shop dedicated to bringing the beauty of nature into your home and life. We offer a curated selection of fresh flowers, vibrant houseplants, and unique botanical gifts, all handpicked with care. Whether you're looking to brighten a space, find the perfect gift, or grow your indoor jungle, we're here to help you nurture your love for all things green.</html>");
        mainpanel.add(confirmlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 320, 180));

        getContentPane().add(mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(USER_aboutus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(USER_aboutus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(USER_aboutus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(USER_aboutus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new USER_aboutus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confirmlbl;
    private javax.swing.JLabel email_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPanel mainpanel;
    // End of variables declaration//GEN-END:variables
}
