/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package plantapp;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author WINDOWS
 */
public class USER_regfinish extends javax.swing.JFrame {

    /**
     * Creates new form USER_thankyou
     */
    public USER_regfinish() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        email_lbl = new javax.swing.JLabel();
        regfinish = new javax.swing.JButton();
        confirmlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainpanel.setBackground(new java.awt.Color(238, 235, 235));
        mainpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        email_lbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        email_lbl.setForeground(new java.awt.Color(72, 96, 51));
        email_lbl.setText("Thank you!");
        mainpanel.add(email_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        regfinish.setBackground(new java.awt.Color(72, 96, 51));
        regfinish.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        regfinish.setForeground(new java.awt.Color(255, 255, 255));
        regfinish.setText("Return");
        mainpanel.add(regfinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        confirmlbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmlbl.setForeground(new java.awt.Color(72, 96, 51));
        confirmlbl.setText("<html>Your registration has been completed. <br> Please return to the login screen. </html>");
        mainpanel.add(confirmlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        getContentPane().add(mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 510));

        setSize(new java.awt.Dimension(396, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(USER_regfinish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(USER_regfinish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(USER_regfinish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(USER_regfinish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
            
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new USER_regfinish().setVisible(true);
                }
            });
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(USER_regfinish.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(USER_regfinish.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(USER_regfinish.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(USER_regfinish.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confirmlbl;
    private javax.swing.JLabel email_lbl;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JButton regfinish;
    // End of variables declaration//GEN-END:variables
}
