/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package plantapp;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author WINDOWS
 */
public class USER_orders extends javax.swing.JFrame {

    /**
     * Creates new form USER_login
     */
    public USER_orders() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainpanel = new javax.swing.JPanel();
        email_lbl = new javax.swing.JLabel();
        loginbtn1 = new javax.swing.JButton();
        loginbtn2 = new javax.swing.JButton();
        email_lbl2 = new javax.swing.JLabel();
        email_lbl3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainpanel.setBackground(new java.awt.Color(238, 235, 235));
        mainpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        email_lbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        email_lbl.setForeground(new java.awt.Color(72, 96, 51));
        email_lbl.setText("Make an Order");
        mainpanel.add(email_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        loginbtn1.setBackground(new java.awt.Color(72, 96, 51));
        loginbtn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginbtn1.setForeground(new java.awt.Color(255, 255, 255));
        loginbtn1.setText("Log Out");
        mainpanel.add(loginbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 300, -1));

        loginbtn2.setBackground(new java.awt.Color(72, 96, 51));
        loginbtn2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginbtn2.setForeground(new java.awt.Color(255, 255, 255));
        loginbtn2.setText("Make an order");
        mainpanel.add(loginbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 300, -1));

        email_lbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email_lbl2.setForeground(new java.awt.Color(72, 96, 51));
        email_lbl2.setText("Looking to get something?");
        mainpanel.add(email_lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        email_lbl3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email_lbl3.setForeground(new java.awt.Color(72, 96, 51));
        email_lbl3.setText("Done for now?");
        mainpanel.add(email_lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        getContentPane().add(mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 330, 760));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 760));

        setSize(new java.awt.Dimension(1063, 765));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(USER_orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(USER_orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(USER_orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(USER_orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
            
            
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new USER_orders().setVisible(true);
                }
            });
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(USER_orders.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(USER_orders.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(USER_orders.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(USER_orders.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel email_lbl;
    private javax.swing.JLabel email_lbl2;
    private javax.swing.JLabel email_lbl3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loginbtn1;
    private javax.swing.JButton loginbtn2;
    private javax.swing.JPanel mainpanel;
    // End of variables declaration//GEN-END:variables
}
